# Generated by Django 3.2 on 2022-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Profile Photo'),
        ),
    ]
