# Generated by Django 3.2 on 2022-08-08 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('photo', models.ImageField(upload_to='services-rest/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='services-rest/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'OrderPhoto',
                'verbose_name_plural': 'OrderPhotos',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('photo', models.ImageField(upload_to='services-rest/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('coverPhoto', models.ImageField(upload_to='services-rest/', verbose_name='Cover Photo')),
                ('icon', models.ImageField(upload_to='services-rest//', verbose_name='Icon')),
                ('averagePrice', models.IntegerField(verbose_name='Average Field')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Tasker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('coverPhoto', models.ImageField(upload_to='services-rest/', verbose_name='Cover Photo')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rating')),
                ('completedTaskCount', models.IntegerField(default=0, verbose_name='Completed Tasks')),
                ('isAvailable', models.BooleanField(default=True, verbose_name='Is Available')),
                ('topTasker', models.BooleanField(default=False, verbose_name='Top Tasker')),
                ('supervisor', models.BooleanField(default=False, verbose_name='Top Tasker')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('certificates', models.ManyToManyField(blank=True, to='core.Certificate', verbose_name='Certificates')),
                ('portofilos', models.ManyToManyField(blank=True, to='core.Portfolio', verbose_name='Portofilos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('workCities', models.ManyToManyField(blank=True, to='core.City', verbose_name='Work Cities')),
            ],
            options={
                'verbose_name': 'Tasker',
                'verbose_name_plural': 'Taskers',
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('coverPhoto', models.ImageField(upload_to='services-rest/', verbose_name='Cover Photo')),
                ('icon', models.ImageField(upload_to='services-rest/', verbose_name='Icon')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'SubService',
                'verbose_name_plural': 'SubServices',
            },
        ),
        migrations.CreateModel(
            name='ServiceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('type', models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('input', 'Input')], default='radio', max_length=50, verbose_name='Type')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subservice', verbose_name='Sub Service')),
            ],
            options={
                'verbose_name': 'ServiceChoice',
                'verbose_name_plural': 'ServiceChoices',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(verbose_name='Start Date')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('inProgress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=50, verbose_name='Stauts')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Reference')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('photos', models.ManyToManyField(blank=True, to='core.OrderPhoto', verbose_name='Photos')),
                ('subService', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.subservice', verbose_name='Sub Service')),
                ('tasker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tasker', verbose_name='Tasker')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('subService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subservice', verbose_name='Sub Service')),
                ('tasker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tasker', verbose_name='Tasker')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('taskerFiltering', models.BooleanField(default=False, verbose_name='Tasker Filtering')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicechoice', verbose_name='Service Choice')),
            ],
            options={
                'verbose_name': 'ChoiceOption',
                'verbose_name_plural': 'ChoiceOptions',
            },
        ),
    ]
