# Generated by Django 3.2 on 2022-08-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.servicechoice', verbose_name='Service Choice'),
        ),
        migrations.AlterField(
            model_name='servicechoice',
            name='subService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceChoices', to='core.subservice', verbose_name='Sub Service'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subServices', to='core.service', verbose_name='Service'),
        ),
    ]
