# Generated by Django 3.2 on 2022-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220808_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='coverPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='services-rest/', verbose_name='Cover Photo'),
        ),
        migrations.AlterField(
            model_name='tasker',
            name='supervisor',
            field=models.BooleanField(default=False, verbose_name='Supervisor'),
        ),
    ]
