# Generated by Django 3.2 on 2022-08-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220808_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='serviceCharge',
            field=models.IntegerField(default=20, verbose_name='Service Charge'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='serviceType',
            field=models.CharField(choices=[('hourlyPrice', 'Hourly Service'), ('fixedPrice', 'Fixed Price')], default=20, max_length=50, verbose_name='Service Type'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceType', models.CharField(choices=[('hourlyPrice', 'Hourly Service'), ('fixedPrice', 'Fixed Price')], max_length=50, verbose_name='Price Type')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.choiceoption', verbose_name='Option')),
                ('subService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.subservice', verbose_name='Sub Service')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.tasker', verbose_name='Tasker')),
            ],
            options={
                'verbose_name': 'TaskerSkill',
                'verbose_name_plural': 'TaskerSkills',
            },
        ),
    ]
