# Generated by Django 3.2 on 2022-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_option_choiceoption_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='Reference'),
        ),
    ]
