# Generated by Django 3.2 on 2022-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='options',
        ),
        migrations.AddField(
            model_name='order',
            name='options',
            field=models.ManyToManyField(to='core.ChoiceOption', verbose_name='Options'),
        ),
    ]
